language: python
dist: xenial
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy3.5-6.0
addons:
  apt:
    packages:
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
install:
  - pip install .[develop]
script:
  - echo $TERM
  - flake8
  - python setup.py test --addopts "--cov gmpy_ctypes"
  - codecov
notifications:
  email: false
